### ISSUE TITLE
Fix recursive issue

### ISSUE THREAD

**Issue by gmoskovicz** [logstash-plugins/logstash-filter-kv#44] opened 2017-03-08 19:27 UTC
When using the same separator for a recursive kv filter, the output generated is wrong. See: https://discuss.elastic.co/t/kv-plugin-recursive-bug/52452.

Easy repro steps:

```
filter { 
  kv { 
    source => "message" 
    recursive => true 
    field_split => "," 
    value_split => "=" 
   } 
} 

```

Use the following input: `a=1,b=2,c=[d=3,e=4,f=[g=5,h=6]] `.

You will see that the result is wrongly generated.

**Comment by gmoskovicz** [comment] 2017-03-08 19:27
@ph do you think that this can be fixed? or using different recursive separators is the actual fix?

**Comment by Shaoranlaos** [comment] 2018-04-11 09:25
this bug still exists in 4.1.0 (Logstash Version 6.2.3)

**Comment by colinsurprenant** [comment] 2019-08-05 20:01
To me this is not a bug and kv will not be able to parse this. IMO the value splitting will necessarily conflict between with the nested values. Any suggestions @yaauie ?

Closing. Please feel free to reopen in needed.

**Closed by colinsurprenant** 2019-08-05 20:01 UTC
Labels: bug
