### ISSUE TITLE
KV filter splitting on a field_split value within data

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-kv#9] opened 2015-05-18 04:58 UTC
(This issue was originally filed by @markwalkom at https://github.com/elastic/logstash/issues/2458)

---

If I have a KV document similar to this;

``` csv
"sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom"
```

And a LS config like;

```
input {
  stdin {}
}

filter {
  kv {
    trim => "\""
    trimkey => "\"\ \(\)"
    field_split => ","
    value_split => ":"
    }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

The `sentence` field is split at the first comma which ends up dividing the string value and the loss of the data in the output;

``` bash
$ echo ""sentence": "the quick brown fox, jumped over the duck", "author": "Mark Walkom""|bin/logstash agent -f kvbug.conf
Using milestone 2 filter plugin 'kv'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
{
       "message" => "sentence: the quick brown fox, jumped over the duck, author: Mark Walkom",
      "@version" => "1",
    "@timestamp" => "2015-01-28T02:47:22.726Z",
          "host" => "bender.local",
      "sentence" => " the quick brown fox",
        "author" => " Mark Walkom"
}
```

Ideally it shouldn't do this and my `sentence` field would be complete.

**Comment by Mister-X-** [comment] 2015-05-19 01:26
It can be reproduced with a simpler configuration. Basically, empty (and using defaults).

Here is the message:
```
date=2015-05-18 time=14:13:48 devname=FG140XXXX devid=FG140XXXXT logid=0100044547 type=event subtype=system level=information vd="VirtualDomain" logdesc="Configure object attribute" user="user1" ui="jsconsole" action=Edit cfgtid=1790967809 cfgpath="system.wccp" cfgobj="101" cfgattr="password[ENC K7taRRarXYdpNvARTqktIeNcecPbJB6gsRQPLKjjftFAj81qnhoGStE4PKI9PGjYodn/Z/f26bcGG0FDpsq4scGzMONwrNuV973xkizVF/YawO8kDmdAlCJeFVHJG99J1gwVhxqjz6cmWSF5aI6FcgAfyk4gjh4yJe0p/oWks3bXxCT2Q/6juahXAIqBtIY9ZJCMJw==->ENC K7taRTt0SmYF1SbAdZes1UJbKzwzFyD/0nrlQ6JHH0Dir6kdtDCtdrT5f9/GfwxmkmAS7hNS+Tidmrrczxf1FNdedgIQIt6gVx+C1J63RWtOp+D68aDScOgBXkO05An3o8EGo4+GyYIr1yUtG1QEGYlbJ7ZhTkYNmpxCi55PdHFZeGROMjvhfB7cSwsGjHpskFk4ug==]" msg="Edit system.wccp 101"
```

It splits the value of cfgattr and think it's several key-values (and we end up with weird keys in ElasticSearch).

**Comment by PhilippWoe** [comment] 2015-08-19 12:43
Same here. Really sucks.The value of value_split is put into /((?:\\\\ |[^,  PLACEHOLDER])+)[PLACEHOLDER](?:\"([^\"]+)\"|'([^']+)'|((?:\\\\ |[^,  ])+))/"} . What doesn't offer a lot control of how it work. It's even not able to hack around because it's placed 2 times in the regex. A simple exact_value_split option would totally do the job...

**Comment by PhilippWoe** [comment] 2015-08-19 12:44
Ok the regex looks different, github removed some stuff when posting the message. Here a pic of the regex
![screen shot 2015-08-19 at 14 44 19](https://cloud.githubusercontent.com/assets/10595770/9356409/d003cc84-4680-11e5-8d9d-4583b1bde26d.png)

**Comment by robyn-kozierok** [comment] 2015-08-25 18:52
I am having this exact problem (except that my field_split is " " and I have spaces in my quoted value strings).  Is there any work-around for this?

**Comment by PhilippWoe** [comment] 2015-08-25 20:08
I did need it for nginx access logs, I ended up with `value_split => '>'` and `field_split => ', '. For nginx access log it seems to work for now. But yeah, it's not really robust..

**Comment by AlexBaker-** [comment] 2016-01-29 10:43
Looking into this.  Here's what I got thus far:

```
  def register
    @trim_re = Regexp.new("[#{@trim}]") if @trim
    @trimkey_re = Regexp.new("[#{@trimkey}]") if @trimkey

    regex_reserved = ['!', '$', '^', '*', '(', ')', '[', ']', '?', '|', '+', '.', '\\']
    field_split_clean = ""
    @field_split.split('').each do|c|
      field_split_clean += (regex_reserved.include?(c) ? "\\" : "") + c
    end
    value_split_clean = (regex_reserved.include?(@value_split) ? "\\" : "") + @value_split

    valueRxString = "(?:\"([^\"]+)\"|'([^']+)'"
    valueRxString += "|\\(([^\\)]+)\\)|\\[([^\\]]+)\\]" if @include_brackets
    valueRxString += "|((?:\\\\ )|.*?)(?:(?=" + field_split_clean + "(?:(?:\\\\ |[^" + field_split_clean + value_split_clean + "])+)" + value_split_clean + ")|$))"
    @scan_re = Regexp.new("[" + field_split_clean + "]?((?:\\\\ |[^" + field_split_clean + value_split_clean + "])+)\s*[" + value_split_clean + "]\s*" + valueRxString)
    @value_split_re = /[#{@value_split}]/
  end
```

It *almost* works, however 6 of 37 tests are failing.  Still digging, but any suggestions would be welcome.

**Comment by shashankcg** [comment] 2016-10-20 23:14
Any updates here? I don't see it working in 5.0 either. I also tried updating my plugin and there weren't any. The kv filter plugin is in version 3.1.1

My input looks like this:
key1=55, key2=qqq\\\\,www\\\\\\\\eee, key3=value3

The escaped comma character in "qqq\\\\,www\\\\\\\\eee" is not considered and we end up losing the following string "www\\\\\\\\eee" for key2.

**Comment by fbaligand** [comment] 2016-11-06 15:00
I just tried @jordansissel  example and it works fine.
By the way, `trim => "\""` is useless (because done by default)
I obtain this :
```
      "sentence" => "the quick brown fox, jumped over the duck",
        "author" => "Mark Walkom"
```

**Comment by fbaligand** [comment] 2016-11-06 16:43
@shashankcg 
If you wish that field separator is not considered if escaped, it is a different need that those expressed by @jordansissel in this issue.
If you need that precisely, I invite you to open a specific issue for that.

Else, you can reach you goal if your input is ` key1=55, key2="qqq,www\\\\eee", key3=value3`

**Comment by kiranmai444** [comment] 2017-05-29 11:05
I want to grok logs with repeated fields like

[2017-05-29 02:17:18] INFO – [ActivityServiceRest:89] – [{“callId”:”kjwefkjweqkfb”},{“callId”:”nwekgwnkqgkqr”},{“callId”:”ohjiwnwbnwbrk”}]

I want to capture all the callId's into a field called call_Id

where the number of times callId appears is dynamic. Can someone please help.

**Comment by markwalkom** [comment] 2017-05-29 20:58
@kiranmai444 you should post that to https://discuss.elastic.co

**Comment by elvarb** [comment] 2017-10-13 11:28
When I have the KV filter run against this string

`last="3367" post="" ltime="3"`

Instead of ending up with

```
last: 3367
post: " ltime="3
```
I end up with

```
last: 3367
post: \
ltime: \"3"
```

I am expecting the KV filter to accept \ as an escape characters so that the value is encapsulated by the non escaped quotation marks but it seems that the kv seperator process kicks in before the kv value is read completely.

**Comment by sevdog** [comment] 2019-01-07 16:47
Any news regarding this issue?

**Comment by colinsurprenant** [comment] 2019-08-05 20:14
This works
```
input {
  stdin {}
}

filter {
  kv {
    trim_key => "\"\ \(\)"
    field_split => ","
    value_split => ":"
    }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

```
{
      "sentence" => "the quick brown fox, jumped over the duck",
        "author" => "Mark Walkom",
       "message" => "\"sentence\": \"the quick brown fox, jumped over the duck\", \"author\": \"Mark Walkom\"",
      "@version" => "1",
          "host" => "mbp15r.local",
    "@timestamp" => 2019-08-05T20:13:41.410Z
}
```

Closing.

**Closed by colinsurprenant** 2019-08-05 20:14 UTC
